routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('sales_teams','SalesTeamController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/SalesTeam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SalesTeam extends Model
{
    use SoftDeletes;

    public function salesTeamRoute(){
        return $this->belongsTo('App\SalesTeamRoute');
    }
}

app/SalesTeamRoute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SalesTeamRoute extends Model
{
    use SoftDeletes;

    public function salesTeam(){
        return $this->hasMany('App\SalesTeam');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SalesTeamController.php
<?php

namespace App\Http\Controllers;

use App\SalesTeam;
use App\SalesTeamRoute;
use Illuminate\Http\Request;

class SalesTeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $teams = SalesTeam::withoutTrashed()->paginate(5);
        return view('salesTeam', compact('teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $routes = SalesTeamRoute::withoutTrashed()->get();
        return view('salesTeamAdd', compact('routes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $res = $request->validate([
            'fullName' => 'required',
            'email' => 'required',
            'telephone' => 'required',
            'dateOfJoined' => 'required|date',
            'currentRoute' => 'required',
        ]);
        $team = new SalesTeam();

        $team->fullName = $request->fullName;
        $team->email = $request->email;
        $team->telephone = $request->telephone;
        $team->dateOfJoined = $request->dateOfJoined;
        $team->currentRoute = $request->currentRoute;
        $team->comment = $request->comment;
        $res = $team->save();

        return redirect(route('sales_teams.index'))->with('success', 'Team Member Added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SalesTeam  $salesTeam
     * @return \Illuminate\Http\Response
     */
    public function show(SalesTeam $salesTeam)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SalesTeam  $salesTeam
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(SalesTeam $salesTeam)
    {
        $routes = SalesTeamRoute::withoutTrashed()->get();
        return view('salesTeamEdit',compact('salesTeam', 'routes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SalesTeam  $salesTeam
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, SalesTeam $salesTeam)
    {
        $res = $request->validate([
            'fullName' => 'required',
            'email' => 'required',
            'telephone' => 'required',
            'dateOfJoined' => 'required|date',
            'currentRoute' => 'required',
        ]);


        $salesTeam->fullName = $request->fullName;
        $salesTeam->email = $request->email;
        $salesTeam->telephone = $request->telephone;
        $salesTeam->dateOfJoined = $request->dateOfJoined;
        $salesTeam->currentRoute = $request->currentRoute;
        $salesTeam->comment = $request->comment;
        $res = $salesTeam->update();

        return redirect(route('sales_teams.index'))->with('success', 'Team Member Added Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SalesTeam  $salesTeam
     * @return \Illuminate\Http\Response
     */
    public function destroy(SalesTeam $salesTeam)
    {
        //
    }
}

app/Http/Controllers/SalesTeamRouteController.php
<?php

namespace App\Http\Controllers;

use App\SalesTeamRoute;
use Illuminate\Http\Request;

class SalesTeamRouteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SalesTeamRoute  $salesTeamRoute
     * @return \Illuminate\Http\Response
     */
    public function show(SalesTeamRoute $salesTeamRoute)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SalesTeamRoute  $salesTeamRoute
     * @return \Illuminate\Http\Response
     */
    public function edit(SalesTeamRoute $salesTeamRoute)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SalesTeamRoute  $salesTeamRoute
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SalesTeamRoute $salesTeamRoute)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SalesTeamRoute  $salesTeamRoute
     * @return \Illuminate\Http\Response
     */
    public function destroy(SalesTeamRoute $salesTeamRoute)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    You are logged in!
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container-fluid">
            <div class="card">

                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3 left-panel">
                            <div class="list-group">
                                <a class="list-group-item" href="{{ route('sales_teams.index') }}">Sales Team</a>
                            </div>
                        </div>
                        <div class="col-md-9">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
</body>
</html>

resources/views/salesTeam.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            Team
            <a href="{{ route('sales_teams.create') }}" class="btn btn-primary float-right">Add New</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">email</th>
                    <th scope="col">Telephone</th>
                    <th scope="col">Current Route</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($teams as $key => $team)
                    <tr>
                        <th scope="row">{{ $key+1 }}</th>
                        <td>{{ $team->fullName }}</td>
                        <td>{{ $team->email }}</td>
                        <td>{{ $team->telephone }}</td>
                        <td>{{ $team->currentRoute }}</td>
                        <td>
                            <a href="{{ route('sales_teams.show', $team->id) }}" class="text-info">View</a> |
                            <a href="{{ route('sales_teams.edit', $team->id) }}" class="text-warning">Edit</a> |
                            <a href="{{ route('sales_teams.destroy', $team->id) }}" class="text-danger">Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="pull-right">{{ $teams->links() }}</div>
        </div>
    </div>

@endsection

resources/views/salesTeamAdd.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            Add New Sales Representative
        </div>
        <div class="card-body">
            <form action="{{ route('sales_teams.store') }}" method="post" id="createMember" enctype="application/x-www-form-urlencoded">
                @csrf
                <div class="form-group">
                    <label for="fullName">Full Name</label>
                    <input type="text" class="form-control" id="fullName" name="fullName" placeholder="Full Name">
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <label for="tele">Telephone</label>
                    <input type="text" class="form-control" id="telephone" name="telephone" placeholder="Telephone" max="15">
                </div>
                <div class="form-group">
                    <label for="dateOfJoined">Joined Date</label>
                    <input type="date" class="form-control" id="dateOfJoined" name="dateOfJoined">
                </div>
                <div class="form-group">
                    <label for="currentRoute">Current Route</label>
                    <select class="form-control" id="currentRoute" name="currentRoute">
                        @foreach($routes as $key=>$route)
                            <option value="{{ $route->id }}">{{ $route->route }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/salesTeamEdit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            Add New Sales Representative
        </div>
        <div class="card-body">
            <form action="{{ route('sales_teams.update', $salesTeam->id) }}" method="put" id="createMember" enctype="application/x-www-form-urlencoded">
                @csrf
                <input type="hidden" id="id" name="id" value="{{ $salesTeam->id }}">
                <div class="form-group">
                    <label for="fullName">Full Name</label>
                    <input type="text" class="form-control" id="fullName" name="fullName" placeholder="Full Name" value="{{ $salesTeam->fullName }}">
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" value="{{ $salesTeam->email }}">
                </div>
                <div class="form-group">
                    <label for="tele">Telephone</label>
                    <input type="text" class="form-control" id="tele" name="tele" placeholder="Telephone" max="15" value="{{ $salesTeam->telephone }}">
                </div>
                <div class="form-group">
                    <label for="dateOfJoined">Joined Date</label>
                    <input type="date" class="form-control" id="dateOfJoined" name="dateOfJoined" value="{{ $salesTeam->dateOfJoined }}">
                </div>
                <div class="form-group">
                    <label for="currentRoute">Current Route</label>
                    <select class="form-control" id="currentRoute" name="currentRoute">
                        @foreach($routes as $key=>$route)
                            <option value="{{ $route->id }}" @if($salesTeam->currentRoute == $route->id) selected @endif>{{ $route->route }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3" >{{ $salesTeam->comment }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection